# Import

In [18]:
import random
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import numpy as np
import category_encoders as ce
import matplotlib.pyplot as plt
from tqdm import tqdm
from tqdm.notebook import tqdm_notebook
tqdm_notebook.pandas(desc="Processing:")

In [2]:
df = pd.read_csv("../input/train.csv")
df_test = pd.read_csv("../input/test.csv")

In [3]:
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0,3189,40,8,30,13,3270,206,234,193,...,0,0,0,0,0,0,0,0,0,1
1,1,3026,182,5,280,29,3270,233,240,106,...,0,0,0,0,0,0,0,0,0,2
2,2,3106,13,7,351,37,2914,208,234,137,...,0,0,0,0,0,0,0,0,0,1
3,3,3022,276,13,192,16,3034,207,238,156,...,0,0,0,0,0,0,0,0,0,2
4,4,2906,186,13,266,22,2916,231,231,154,...,0,0,0,0,0,0,0,0,0,2

In [4]:
print(len(df))
print(len(df_test))

4000000
1000000

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,4000000.0,2.000000e+06,1.154701e+06,0.0,999999.75,1999999.5,2999999.25,3999999.0
Elevation,4000000.0,2.980192e+03,2.890482e+02,1773.0,2760.00,2966.0,3217.00,4383.0
Aspect,4000000.0,1.515857e+02,1.099611e+02,-33.0,60.00,123.0,247.00,407.0
Slope,4000000.0,1.509754e+01,8.546731e+00,-3.0,9.00,14.0,20.00,64.0
Horizontal_Distance_To_Hydrology,4000000.0,2.713154e+02,2.265497e+02,-92.0,110.00,213.0,361.00,1602.0
Vertical_Distance_To_Hydrology,4000000.0,5.166262e+01,6.821597e+01,-317.0,4.00,31.0,78.00,647.0
Horizontal_Distance_To_Roadways,4000000.0,1.766642e+03,1.315610e+03,-287.0,822.00,1436.0,2365.00,7666.0
Hillshade_9am,4000000.0,2.118375e+02,3.075996e+01,-4.0,198.00,218.0,233.00,301.0
Hillshade_Noon,4000000.0,2.210614e+02,2.223134e+01,49.0,210.00,224.0,237.00,279.0
Hillshade_3pm,4000000.0,1.408109e+02,4.369864e+01,-53.0,115.00,142.0,169.00,272.0
Horizontal_Distance_To_Fire_Points,4000000.0,1.581407e+03,1.127616e+03,-277.0,781.00,1361.0,2084.00,8075.0
Wilderness_Area1,4000000.0,2.611930e-01,4.392849e-01,0.0,0.00,0.0,1.00,1.0
Wilderness_Area2,4000000.0,4.166100e-02,1.998133e-01,0.0,0.00,0.0,0.00,1.0
Wilderness_Area3,4000000.0,6.535732e-01,4.758312e-01,0.0,0.00,1.0,1.00,1.0
Wilderness_Area4,4000000.0,2.181900e-02,1.460922e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type1,4000000.0,1.684150e-02,1.286774e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type2,4000000.0,3.089600e-02,1.730360e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type3,4000000.0,4.275500e-03,6.524738e-02,0.0,0.00,0.0,0.00,1.0
Soil_Type4,4000000.0,3.791275e-02,1.909853e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type5,4000000.0,1.571525e-02,1.243716e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type6,4000000.0,7.972750e-03,8.893361e-02,0.0,0.00,0.0,0.00,1.0
Soil_Type7,4000000.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.0
Soil_Type8,4000000.0,2.899750e-03,5.377120e-02,0.0,0.00,0.0,0.00,1.0
Soil_Type9,4000000.0,1.089300e-02,1.037995e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type10,4000000.0,5.454075e-02,2.270816e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type11,4000000.0,2.798525e-02,1.649305e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type12,4000000.0,1.829000e-02,1.339981e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type13,4000000.0,3.129525e-02,1.741145e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type14,4000000.0,1.497650e-02,1.214587e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type15,4000000.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.0
Soil_Type16,4000000.0,1.588850e-02,1.250442e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type17,4000000.0,2.067175e-02,1.422829e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type18,4000000.0,1.343625e-02,1.151335e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type19,4000000.0,1.381125e-02,1.167069e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type20,4000000.0,1.736800e-02,1.306383e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type21,4000000.0,1.153900e-02,1.067982e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type22,4000000.0,3.134600e-02,1.742511e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type23,4000000.0,4.917075e-02,2.162244e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type24,4000000.0,2.502175e-02,1.561911e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type25,4000000.0,3.258250e-03,5.698802e-02,0.0,0.00,0.0,0.00,1.0
Soil_Type26,4000000.0,1.352700e-02,1.155163e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type27,4000000.0,1.176575e-02,1.078301e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type28,4000000.0,1.070775e-02,1.029228e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type29,4000000.0,2.227350e-02,1.475717e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type30,4000000.0,2.886700e-02,1.674327e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type31,4000000.0,2.749325e-02,1.635157e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type32,4000000.0,3.746200e-02,1.898910e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type33,4000000.0,3.782075e-02,1.907625e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type34,4000000.0,1.199500e-02,1.088629e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type35,4000000.0,1.605350e-02,1.256813e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type36,4000000.0,1.071275e-02,1.029465e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type37,4000000.0,1.220750e-02,1.098111e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type38,4000000.0,4.075150e-02,1.977140e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type39,4000000.0,3.923925e-02,1.941637e-01,0.0,0.00,0.0,0.00,1.0
Soil_Type40,4000000.0,3.161850e-02,1.749822e-01,0.0,0.00,0.0,0.00,1.0
Cover_Type,4000000.0,1.771335e+00,8.938060e-01,1.0,1.00,2.0,2.00,7.0

In [6]:
pd.concat({
    "unique": df.nunique(),
    "missing": df.isnull().sum(),
    "dtype": df.dtypes,
}, axis=1)

                                     unique  missing  dtype
Id                                  4000000        0  int64
Elevation                              2525        0  int64
Aspect                                  440        0  int64
Slope                                    68        0  int64
Horizontal_Distance_To_Hydrology       1636        0  int64
Vertical_Distance_To_Hydrology          916        0  int64
Horizontal_Distance_To_Roadways        7760        0  int64
Hillshade_9am                           301        0  int64
Hillshade_Noon                          221        0  int64
Hillshade_3pm                           326        0  int64
Horizontal_Distance_To_Fire_Points     8112        0  int64
Wilderness_Area1                          2        0  int64
Wilderness_Area2                          2        0  int64
Wilderness_Area3                          2        0  int64
Wilderness_Area4                          2        0  int64
Soil_Type1                                2        0  int64
Soil_Type2                                2        0  int64
Soil_Type3                                2        0  int64
Soil_Type4                                2        0  int64
Soil_Type5                                2        0  int64
Soil_Type6                                2        0  int64
Soil_Type7                                1        0  int64
Soil_Type8                                2        0  int64
Soil_Type9                                2        0  int64
Soil_Type10                               2        0  int64
Soil_Type11                               2        0  int64
Soil_Type12                               2        0  int64
Soil_Type13                               2        0  int64
Soil_Type14                               2        0  int64
Soil_Type15                               1        0  int64
Soil_Type16                               2        0  int64
Soil_Type17                               2        0  int64
Soil_Type18                               2        0  int64
Soil_Type19                               2        0  int64
Soil_Type20                               2        0  int64
Soil_Type21                               2        0  int64
Soil_Type22                               2        0  int64
Soil_Type23                               2        0  int64
Soil_Type24                               2        0  int64
Soil_Type25                               2        0  int64
Soil_Type26                               2        0  int64
Soil_Type27                               2        0  int64
Soil_Type28                               2        0  int64
Soil_Type29                               2        0  int64
Soil_Type30                               2        0  int64
Soil_Type31                               2        0  int64
Soil_Type32                               2        0  int64
Soil_Type33                               2        0  int64
Soil_Type34                               2        0  int64
Soil_Type35                               2        0  int64
Soil_Type36                               2        0  int64
Soil_Type37                               2        0  int64
Soil_Type38                               2        0  int64
Soil_Type39                               2        0  int64
Soil_Type40                               2        0  int64
Cover_Type                                7        0  int64

In [5]:
from sklearn.feature_selection import mutual_info_classif

In [6]:
X = df.copy().iloc[:10000, 1:]
y = X.pop("Cover_Type")

print(*sorted(zip(X, mutual_info_classif(X, y)), key=lambda x:x[1], reverse=True), sep='\n')

('Elevation', 0.5205651987500557)
('Horizontal_Distance_To_Roadways', 0.02713421798639093)
('Horizontal_Distance_To_Fire_Points', 0.019151139011545304)
('Wilderness_Area1', 0.0173204970329901)
('Soil_Type10', 0.01586376211433871)
('Slope', 0.012951970041891192)
('Soil_Type40', 0.010717848441332833)
('Soil_Type12', 0.009814744574972112)
('Soil_Type32', 0.009112698215733683)
('Soil_Type35', 0.008429813165916178)
('Soil_Type30', 0.008310496019962033)
('Wilderness_Area4', 0.00820151408076697)
('Soil_Type26', 0.007992034554314076)
('Soil_Type21', 0.007567632633680432)
('Hillshade_Noon', 0.007172261724530671)
('Soil_Type22', 0.006840454722235378)
('Soil_Type8', 0.006456902666533537)
('Soil_Type7', 0.00540601800137841)
('Soil_Type3', 0.00526080390659045)
('Soil_Type1', 0.00503965251320615)
('Soil_Type29', 0.00500990096429188)
('Soil_Type9', 0.004853142760782969)
('Hillshade_9am', 0.004837504899395384)
('Soil_Type27', 0.0037371289993872736)
('Soil_Type20', 0.003643230308333134)
('Aspect', 0.0035204567547286736)
('Soil_Type37', 0.0034723843337014504)
('Soil_Type6', 0.0019360378052759586)
('Soil_Type15', 0.001849367612177133)
('Soil_Type31', 0.0018202909445987903)
('Soil_Type4', 0.0015771904760406574)
('Soil_Type17', 0.0012597750131781993)
('Soil_Type5', 0.0012555840126415863)
('Horizontal_Distance_To_Hydrology', 0.0006047638461188498)
('Vertical_Distance_To_Hydrology', 0.0005848353528052908)
('Soil_Type28', 0.00043414876276681724)
('Hillshade_3pm', 0.0)
('Wilderness_Area2', 0.0)
('Wilderness_Area3', 0.0)
('Soil_Type2', 0.0)
('Soil_Type11', 0.0)
('Soil_Type13', 0.0)
('Soil_Type14', 0.0)
('Soil_Type16', 0.0)
('Soil_Type18', 0.0)
('Soil_Type19', 0.0)
('Soil_Type23', 0.0)
('Soil_Type24', 0.0)
('Soil_Type25', 0.0)
('Soil_Type33', 0.0)
('Soil_Type34', 0.0)
('Soil_Type36', 0.0)
('Soil_Type38', 0.0)
('Soil_Type39', 0.0)

In [4]:
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0,3189,40,8,30,13,3270,206,234,193,...,0,0,0,0,0,0,0,0,0,1
1,1,3026,182,5,280,29,3270,233,240,106,...,0,0,0,0,0,0,0,0,0,2
2,2,3106,13,7,351,37,2914,208,234,137,...,0,0,0,0,0,0,0,0,0,1
3,3,3022,276,13,192,16,3034,207,238,156,...,0,0,0,0,0,0,0,0,0,2
4,4,2906,186,13,266,22,2916,231,231,154,...,0,0,0,0,0,0,0,0,0,2

In [5]:
df["Distance_To_Hydrology"] = df["Horizontal_Distance_To_Hydrology"]**2 + df["Vertical_Distance_To_Hydrology"]**2
df["Distance_To_Hydrology"]

0            1069
1           79241
2          124570
3           37120
4           71240
            ...
3999995      6826
3999996    491305
3999997    262445
3999998    148772
3999999      2017
Name: Distance_To_Hydrology, Length: 4000000, dtype: int64

In [6]:
df["diff_roadways_and_hydrology"] = df["Horizontal_Distance_To_Roadways"] - df["Horizontal_Distance_To_Hydrology"]
df["diff_roadways_and_hydrology"]

0          3240
1          2990
2          2563
3          2842
4          2650
           ...
3999995    6263
3999996    4731
3999997    4311
3999998    2216
3999999    1631
Name: diff_roadways_and_hydrology, Length: 4000000, dtype: int64

In [7]:
hillshade_columns = [
    "Hillshade_9am",
    "Hillshade_Noon",
    "Hillshade_3pm"
]

df["sum_Hillshade"] = df[hillshade_columns].sum(axis=1)
df["sum_Hillshade"]

0          633
1          579
2          579
3          601
4          616
          ...
3999995    580
3999996    576
3999997    478
3999998    447
3999999    615
Name: sum_Hillshade, Length: 4000000, dtype: int64

In [8]:
from itertools import combinations

for col0, col1 in combinations(hillshade_columns, 2):
    df[f"diff_{col0}_{col1}"] = df[col0] - df[col1]

df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type,Distance_To_Hydrology,diff_roadways_and_hydrology,sum_Hillshade,diff_Hillshade_9am_Hillshade_Noon,diff_Hillshade_9am_Hillshade_3pm,diff_Hillshade_Noon_Hillshade_3pm
0,0,3189,40,8,30,13,3270,206,234,193,...,0,0,0,1,1069,3240,633,-28,13,41
1,1,3026,182,5,280,29,3270,233,240,106,...,0,0,0,2,79241,2990,579,-7,127,134
2,2,3106,13,7,351,37,2914,208,234,137,...,0,0,0,1,124570,2563,579,-26,71,97
3,3,3022,276,13,192,16,3034,207,238,156,...,0,0,0,2,37120,2842,601,-31,51,82
4,4,2906,186,13,266,22,2916,231,231,154,...,0,0,0,2,71240,2650,616,0,77,77

In [9]:
wilderness_columns = [f"Wilderness_Area{i}" for i in range(1, 5)]

df["sum_Wilderness"] = df[wilderness_columns].sum(axis=1)
df["sum_Wilderness"]

0          1
1          1
2          1
3          1
4          1
          ..
3999995    1
3999996    0
3999997    1
3999998    1
3999999    0
Name: sum_Wilderness, Length: 4000000, dtype: int64

In [10]:
df["class_Wilderness"] = 0
for i in range(1, 5):
    df["class_Wilderness"] += df[f"Wilderness_Area{i}"] * (1 << (i - 1))

df["class_Wilderness"].value_counts()

4     2481478
1      951643
0      247032
8       86305
2       73674
5       66853
6       65768
3       26127
10        926
7         149
12         45
Name: class_Wilderness, dtype: int64

In [12]:
df.drop(wilderness_columns, axis=1, inplace=True)

df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Cover_Type,Distance_To_Hydrology,diff_roadways_and_hydrology,sum_Hillshade,diff_Hillshade_9am_Hillshade_Noon,diff_Hillshade_9am_Hillshade_3pm,diff_Hillshade_Noon_Hillshade_3pm,sum_Wilderness,class_Wilderness,count_Wilderness
0,0,3189,40,8,30,13,3270,206,234,193,...,1,1069,3240,633,-28,13,41,1,1,951643
1,1,3026,182,5,280,29,3270,233,240,106,...,2,79241,2990,579,-7,127,134,1,1,951643
2,2,3106,13,7,351,37,2914,208,234,137,...,1,124570,2563,579,-26,71,97,1,1,951643
3,3,3022,276,13,192,16,3034,207,238,156,...,2,37120,2842,601,-31,51,82,1,1,951643
4,4,2906,186,13,266,22,2916,231,231,154,...,2,71240,2650,616,0,77,77,1,1,951643

In [13]:
soil_columns = [f"Soil_Type{i}" for i in range(1, 41)]

df["sum_Soil"] = df[soil_columns].sum(axis=1)
df["sum_Soil"]

0          1
1          1
2          1
3          1
4          1
          ..
3999995    1
3999996    1
3999997    2
3999998    0
3999999    0
Name: sum_Soil, Length: 4000000, dtype: int64

In [14]:
important_soil_columns = [f"Soil_Type{i}" for i in (11, 13, 22, 23, 24, 31, 32, 33, 35, 36, 37, 38, 39, 40)]

df["important_sum_Soil"] = df[important_soil_columns].sum(axis=1)
df["important_sum_Soil"]

0          0
1          0
2          0
3          0
4          0
          ..
3999995    0
3999996    1
3999997    1
3999998    0
3999999    0
Name: important_sum_Soil, Length: 4000000, dtype: int64

In [15]:
df["class_Soil_Type"] = 0

for i, col in enumerate(important_soil_columns):
    df["class_Soil_Type"] += df[col] * (1 << i)

df["class_Soil_Type"].value_counts()

0       2592110
8        140536
2048     113245
128      108748
64       107701
         ...
1538          1
4180          1
2322          1
1218          1
2337          1
Name: class_Soil_Type, Length: 1218, dtype: int64

In [19]:
df.drop(soil_columns, axis=1, inplace=True)

KeyError: "['Soil_Type1' 'Soil_Type2' 'Soil_Type3' 'Soil_Type4' 'Soil_Type5'\n 'Soil_Type6' 'Soil_Type7' 'Soil_Type8' 'Soil_Type9' 'Soil_Type10'\n 'Soil_Type11' 'Soil_Type12' 'Soil_Type13' 'Soil_Type14' 'Soil_Type15'\n 'Soil_Type16' 'Soil_Type17' 'Soil_Type18' 'Soil_Type19' 'Soil_Type20'\n 'Soil_Type21' 'Soil_Type22' 'Soil_Type23' 'Soil_Type24' 'Soil_Type25'\n 'Soil_Type26' 'Soil_Type27' 'Soil_Type28' 'Soil_Type29' 'Soil_Type30'\n 'Soil_Type31' 'Soil_Type32' 'Soil_Type33' 'Soil_Type34' 'Soil_Type35'\n 'Soil_Type36' 'Soil_Type37' 'Soil_Type38' 'Soil_Type39' 'Soil_Type40'] not found in axis"

In [20]:
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type,Distance_To_Hydrology,diff_roadways_and_hydrology,sum_Hillshade,diff_Hillshade_9am_Hillshade_Noon,diff_Hillshade_9am_Hillshade_3pm,diff_Hillshade_Noon_Hillshade_3pm,sum_Wilderness,class_Wilderness,count_Wilderness,sum_Soil,important_sum_Soil,class_Soil_Type,count_Soil_Type
0,0,3189,40,8,30,13,3270,206,234,193,4873,1,1069,3240,633,-28,13,41,1,1,951643,1,0,0,2592110
1,1,3026,182,5,280,29,3270,233,240,106,5423,2,79241,2990,579,-7,127,134,1,1,951643,1,0,0,2592110
2,2,3106,13,7,351,37,2914,208,234,137,5269,1,124570,2563,579,-26,71,97,1,1,951643,1,0,0,2592110
3,3,3022,276,13,192,16,3034,207,238,156,2866,2,37120,2842,601,-31,51,82,1,1,951643,1,0,0,2592110
4,4,2906,186,13,266,22,2916,231,231,154,2642,2,71240,2650,616,0,77,77,1,1,951643,1,0,0,2592110